
-- DatabaseSetup.sql
-- Updated schema and sample data for the application

-- Drop existing tables if they exist
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE INGREDIENTS CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCT_INGREDIENTS CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE SALES CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE CATEGORIES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Drop sequences if they exist
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE PRODUCT_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE INGREDIENT_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SALES_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Create Categories table
CREATE TABLE CATEGORIES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    TYPE VARCHAR2(20) NOT NULL CHECK (TYPE IN ('상품', '재료'))
);

-- Create Products table
CREATE TABLE PRODUCTS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(50),
    PRICE NUMBER NOT NULL,
    STATUS VARCHAR2(20) DEFAULT '판매 중'
);

-- Create Ingredients table
CREATE TABLE INGREDIENTS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(50),
    STOCK NUMBER NOT NULL,
    UNIT_PRICE NUMBER NOT NULL
);

-- Create Product_Ingredients mapping table
CREATE TABLE PRODUCT_INGREDIENTS (
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    INGREDIENT_ID NUMBER REFERENCES INGREDIENTS(ID) ON DELETE CASCADE,
    QUANTITY NUMBER NOT NULL,
    PRIMARY KEY (PRODUCT_ID, INGREDIENT_ID)
);

-- Create Sales table
CREATE TABLE SALES (
    ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(ID),
    QUANTITY NUMBER NOT NULL,
    SALE_DATE DATE DEFAULT SYSDATE
);

-- Create sequences
CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INGREDIENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SALES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Insert sample categories
INSERT INTO CATEGORIES (ID, NAME, TYPE) VALUES (1, '햄버거', '상품');
INSERT INTO CATEGORIES (ID, NAME, TYPE) VALUES (2, '음료', '상품');
INSERT INTO CATEGORIES (ID, NAME, TYPE) VALUES (3, '사이드', '상품');
INSERT INTO CATEGORIES (ID, NAME, TYPE) VALUES (4, '빵', '재료');
INSERT INTO CATEGORIES (ID, NAME, TYPE) VALUES (5, '채소', '재료');
INSERT INTO CATEGORIES (ID, NAME, TYPE) VALUES (6, '고기', '재료');

-- Insert sample ingredients
INSERT INTO INGREDIENTS (ID, NAME, CATEGORY, STOCK, UNIT_PRICE) VALUES (1, 'Cheese', 'Dairy', 100, 0.75);
INSERT INTO INGREDIENTS (ID, NAME, CATEGORY, STOCK, UNIT_PRICE) VALUES (2, 'Lettuce', '채소', 200, 0.30);
INSERT INTO INGREDIENTS (ID, NAME, CATEGORY, STOCK, UNIT_PRICE) VALUES (3, 'Beef Patty', '고기', 150, 1.50);

-- Insert sample products
INSERT INTO PRODUCTS (ID, NAME, CATEGORY, PRICE, STATUS) VALUES (1, 'Classic Burger', '햄버거', 5.99, '판매 중');
INSERT INTO PRODUCTS (ID, NAME, CATEGORY, PRICE, STATUS) VALUES (2, 'Coke', '음료', 1.49, '판매 중');
INSERT INTO PRODUCTS (ID, NAME, CATEGORY, PRICE, STATUS) VALUES (3, 'Fries', '사이드', 2.99, '판매 중');

-- Insert sample product-ingredients mapping
INSERT INTO PRODUCT_INGREDIENTS (PRODUCT_ID, INGREDIENT_ID, QUANTITY) VALUES (1, 1, 1); -- Cheese
INSERT INTO PRODUCT_INGREDIENTS (PRODUCT_ID, INGREDIENT_ID, QUANTITY) VALUES (1, 2, 1); -- Lettuce
INSERT INTO PRODUCT_INGREDIENTS (PRODUCT_ID, INGREDIENT_ID, QUANTITY) VALUES (1, 3, 1); -- Beef Patty

-- Insert sample sales
INSERT INTO SALES (ID, PRODUCT_ID, QUANTITY, SALE_DATE) VALUES (1, 1, 2, SYSDATE);
INSERT INTO SALES (ID, PRODUCT_ID, QUANTITY, SALE_DATE) VALUES (2, 2, 3, SYSDATE);
INSERT INTO SALES (ID, PRODUCT_ID, QUANTITY, SALE_DATE) VALUES (3, 3, 1, SYSDATE);
